//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewrite_It.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rewrite_It.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Cancel {
            get {
                return ResourceManager.GetStream("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CheckMode {
            get {
                return ResourceManager.GetStream("CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckModeBackground {
            get {
                object obj = ResourceManager.GetObject("CheckModeBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ChosenOption {
            get {
                return ResourceManager.GetStream("ChosenOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Click {
            get {
                return ResourceManager.GetStream("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CursorHovered {
            get {
                return ResourceManager.GetStream("CursorHovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream CursorNotHovered {
            get {
                return ResourceManager.GetStream("CursorNotHovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DoorClose {
            get {
                return ResourceManager.GetStream("DoorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DoorEnter {
            get {
                return ResourceManager.GetStream("DoorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmailBackground {
            get {
                object obj = ResourceManager.GetObject("EmailBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExitFromCheckMode {
            get {
                object obj = ResourceManager.GetObject("ExitFromCheckMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeadBookTab1 {
            get {
                object obj = ResourceManager.GetObject("HeadBookTab1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeadBookTab2 {
            get {
                object obj = ResourceManager.GetObject("HeadBookTab2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeadBookTab3 {
            get {
                object obj = ResourceManager.GetObject("HeadBookTab3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeadEditorBook {
            get {
                object obj = ResourceManager.GetObject("HeadEditorBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HeadEditorBook2 {
            get {
                object obj = ResourceManager.GetObject("HeadEditorBook2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Man1 {
            get {
                object obj = ResourceManager.GetObject("Man1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Man2 {
            get {
                object obj = ResourceManager.GetObject("Man2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распродажа мебели в Daveneil
        ///Реклама
        ///ЦА: покупатели
        ///Мы закрываемся, и у нас глобальная распродажа.
        ///[NoNumbers, С единицами математических величин следует использовать цифровую форму записи: : &quot;80%&quot;.] Обустройте ваш дом с реальной скидкой восемьдесят процентов!
        ///По первому запросу мы покажем вам стоимость аналогичных товаров на сайте конкурентов.
        ///[NoNumbers, С единицами математических величин следует использовать цифровую форму записи: &quot;80%&quot;.] Это честные восемьдесят процентов, а не какая-то там другая  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Marketing1 {
            get {
                return ResourceManager.GetString("Marketing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на компания &quot;Business4You&quot;
        ///Реклама
        ///ЦА: бизнесмены
        ///Приглашаем инвесторов разных отраслей в нашу компанию по менеджменту предприятий.
        ///Компания Business4You уже 12 лет подряд выходит в финал престижного международного конкурса Best Business In Russia. В штате компании 69 человек. 
        ///[TooMuchDetails] Конкурс проводится под эгидой Российского интеллектуального общества. Её руководитель Валерий Ожегов окончил МГУ в возрасте 17 лет, став одним из самых молодых выпускников за последний год.
        ///[TooMuchDetails] Его же [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Marketing2 {
            get {
                return ResourceManager.GetString("Marketing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие магазина &quot;Шар идеальная форма&quot;
        ///Реклама
        ///ЦА: покупатели женской одежды
        ///Магазин &quot;Шар идеальная форма&quot; предлагает одежду больших размеров дамам, имеющим завидные формы. &quot;Шар идеальная форма&quot; является уникальной торговой площадкой с широким ассортиментом от производителей из разных стран.
        ///В магазине собраны модели от известных дизайнеров Турции, России и Беларуси.
        ///Магазин &quot;Шар идеальная форма&quot; позволяет любой моднице получить желаемый товар по доступным ценам. Спешите оформить заказ, и менеджеры ми [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Marketing3 {
            get {
                return ResourceManager.GetString("Marketing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распродажа в магазине &quot;Пластинка&quot;
        ///Реклама
        ///ЦА: молодежь
        ///[PseudoLanguage] Бегом хайпить эту рофло-темку со скидками на пластик. На всех не хватит топ мастхэв стафа. Я сказал, всем покедова. ББ. Раунд!
        ///По случаю закрытия магазина у нас феноменальные скидки в отделе музыкальных интрументов. Они доходят до 30%. В отделе пластинок скидки доходят ДО 15%! (это касается и проигрывателей).
        ///В нашем арсенале представлена разная музыкальная техника, а также и классические интрументы. Но преимущественным направление [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Marketing4 {
            get {
                return ResourceManager.GetString("Marketing4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MissTakeman {
            get {
                object obj = ResourceManager.GetObject("MissTakeman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NewMessage {
            get {
                return ResourceManager.GetStream("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NextPhrase {
            get {
                return ResourceManager.GetStream("NextPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Notebook {
            get {
                object obj = ResourceManager.GetObject("Notebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfficeBackground {
            get {
                object obj = ResourceManager.GetObject("OfficeBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream OfficeBackground1 {
            get {
                return ResourceManager.GetStream("OfficeBackground1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfficeComputer {
            get {
                object obj = ResourceManager.GetObject("OfficeComputer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfficeTable {
            get {
                object obj = ResourceManager.GetObject("OfficeTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Paper {
            get {
                return ResourceManager.GetStream("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperBackground {
            get {
                object obj = ResourceManager.GetObject("PaperBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PixelGeorgia {
            get {
                object obj = ResourceManager.GetObject("PixelGeorgia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Promotion {
            get {
                return ResourceManager.GetStream("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Stamp {
            get {
                return ResourceManager.GetStream("Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Woman1 {
            get {
                object obj = ResourceManager.GetObject("Woman1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Woman2 {
            get {
                object obj = ResourceManager.GetObject("Woman2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Стрелка__исходное_ {
            get {
                object obj = ResourceManager.GetObject("Стрелка__исходное_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
